#ifndef BUNDLE_COMMON_BUNDLE_H
#define BUNDLE_COMMON_BUNDLE_H

typedef long long timestamp_t;
#define BUNDLE_NULL_TIMESTAMP 0
#define BUNDLE_MIN_TIMESTAMP 1
#define BUNDLE_MAX_TIMESTAMP (LLONG_MAX - 1)
#define BUNDLE_BUSY_TIMESTAMP LLONG_MAX

#endif // BUNDLE_COMMON_BUNDLE_H